# Generated by Django 6.0.6 on 2026-06-29 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kingdoms', '0002_alter_event_options_alter_turnhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('peace_offered', 'Peace Offered'), ('ended', 'Ended')], default='active', max_length=20)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars_started', to='kingdoms.kingdom')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars_defended', to='kingdoms.kingdom')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wars_won', to='kingdoms.kingdom')),
            ],
            options={
                'ordering': ['-declared_at'],
            },
        ),
        migrations.CreateModel(
            name='PeaceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peace_offers_sent', to='kingdoms.kingdom')),
                ('offered_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peace_offers_received', to='kingdoms.kingdom')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peace_offers', to='wars.war')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_losses', models.IntegerField(default=0)),
                ('defender_losses', models.IntegerField(default=0)),
                ('outcome', models.CharField(choices=[('attacker_victory', 'Attacker Victory'), ('defender_victory', 'Defender Victory'), ('draw', 'Draw')], max_length=30)),
                ('battle_log', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_battles', to='kingdoms.kingdom')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defending_battles', to='kingdoms.kingdom')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='wars.war')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('attacker', 'Attacker'), ('defender', 'Defender')], max_length=20)),
                ('troops_committed', models.IntegerField(default=0)),
                ('starting_army_quality', models.FloatField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_participations', to='kingdoms.kingdom')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='wars.war')),
            ],
            options={
                'unique_together': {('war', 'kingdom')},
            },
        ),
    ]
