# Generated by Django 6.0.6 on 2026-07-03 22:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdoms', '0003_kingdom_battle_momentum_kingdom_is_at_war_and_more'),
        ('wars', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='warparticipant',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='warparticipant',
            name='war',
        ),
        migrations.RemoveField(
            model_name='war',
            name='ended_at',
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_momentum_modifier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_prestige_modifier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_random_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_strength',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_momentum_modifier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_prestige_modifier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_random_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_strength',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='war',
            name='attacker_ai_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='war',
            name='attacker_inspiration_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='war',
            name='attacker_leadership_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='war',
            name='attacker_practicality_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='war',
            name='attacker_rally_modifier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='war',
            name='attacker_rallying_cry',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='war',
            name='defender_ai_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='war',
            name='defender_auto_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='war',
            name='defender_inspiration_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='war',
            name='defender_leadership_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='war',
            name='defender_practicality_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='war',
            name='defender_rally_modifier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='war',
            name='defender_rallying_cry',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='war',
            name='defender_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='war',
            name='defender_response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 4, 0, 59, 44, 327366, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='war',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='attacker_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battle',
            name='defender_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battle',
            name='war',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle', to='wars.war'),
        ),
        migrations.AlterField(
            model_name='war',
            name='defender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars_received', to='kingdoms.kingdom'),
        ),
        migrations.AlterField(
            model_name='war',
            name='status',
            field=models.CharField(choices=[('pending_defender', 'Pending Defender Response'), ('resolved', 'Resolved')], default='pending_defender', max_length=30),
        ),
        migrations.AlterField(
            model_name='war',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wars_won_records', to='kingdoms.kingdom'),
        ),
        migrations.CreateModel(
            name='WarCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooldown_ends_at', models.DateTimeField()),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_cooldowns_started', to='kingdoms.kingdom')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_cooldowns_received', to='kingdoms.kingdom')),
            ],
            options={
                'unique_together': {('attacker', 'defender')},
            },
        ),
        migrations.DeleteModel(
            name='PeaceOffer',
        ),
        migrations.DeleteModel(
            name='WarParticipant',
        ),
    ]
