# Generated by Django 6.0.6 on 2026-07-04 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0002_alter_warparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='war',
            name='defender_responded_at',
        ),
        migrations.AlterField(
            model_name='war',
            name='defender_response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 4, 19, 0, 36, 95528, tzinfo=datetime.timezone.utc)),
        ),
    ]
