# Generated by Django 6.0.6 on 2026-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0003_remove_war_defender_responded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='battle_log',
        ),
        migrations.AddField(
            model_name='battle',
            name='report_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='war',
            name='defender_response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
