# Generated by Django 6.0.6 on 2026-06-24 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('population_change', models.IntegerField(default=0)),
                ('treasury_change', models.FloatField(default=0)),
                ('happiness_change', models.FloatField(default=0)),
                ('stability_change', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_input', models.TextField()),
                ('empathy', models.FloatField()),
                ('practicality', models.FloatField()),
                ('leadership', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response', to='kingdoms.event')),
            ],
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ruler_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('population', models.IntegerField(default=1000)),
                ('treasury', models.FloatField(default=500)),
                ('food', models.FloatField(default=1000)),
                ('happiness', models.FloatField(default=50)),
                ('stability', models.FloatField(default=50)),
                ('army_size', models.IntegerField(default=100)),
                ('army_quality', models.FloatField(default=1.0)),
                ('tax_rate', models.FloatField(default=20)),
                ('agriculture_investment', models.FloatField(default=25)),
                ('infrastructure_investment', models.FloatField(default=25)),
                ('military_investment', models.FloatField(default=25)),
                ('welfare_investment', models.FloatField(default=25)),
                ('a_eff', models.FloatField(default=1.0)),
                ('infra', models.FloatField(default=1.0)),
                ('turn_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kingdom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='kingdoms.kingdom'),
        ),
        migrations.CreateModel(
            name='TurnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField()),
                ('population', models.IntegerField()),
                ('treasury', models.FloatField()),
                ('food', models.FloatField()),
                ('happiness', models.FloatField()),
                ('stability', models.FloatField()),
                ('army_size', models.IntegerField()),
                ('army_quality', models.FloatField()),
                ('a_eff', models.FloatField()),
                ('infra', models.FloatField()),
                ('tax_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kingdoms.kingdom')),
            ],
        ),
    ]
