# Generated by Django 6.0.6 on 2026-06-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdoms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'turn_number', 'ordering': ['turn_number']},
        ),
        migrations.AlterModelOptions(
            name='turnhistory',
            options={'get_latest_by': 'turn_number', 'ordering': ['turn_number']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='happiness_change',
        ),
        migrations.RemoveField(
            model_name='event',
            name='population_change',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stability_change',
        ),
        migrations.RemoveField(
            model_name='event',
            name='treasury_change',
        ),
        migrations.AddField(
            model_name='event',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='applied_effects',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='empathy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='leadership',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='player_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='practicality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='report_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='turn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='kingdoms.turnhistory'),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='famine_turns_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='food_production_modifier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='territory_count',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='turnhistory',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('famine', 'Famine'), ('riot', 'Riot'), ('rebellion', 'Rebellion'), ('market_crash', 'Market Crash'), ('desertion', 'Desertion')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AIResponse',
        ),
    ]
