# Generated by Django 6.0.6 on 2026-07-03 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdoms', '0002_alter_event_options_alter_turnhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingdom',
            name='battle_momentum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='is_at_war',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='prestige',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='turns_remaining',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='war_available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='wars_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='wars_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turnhistory',
            name='report_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TurnLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_turn_limit', models.IntegerField(default=3)),
                ('turns_remaining_today', models.IntegerField(default=3)),
                ('cooldown_minutes', models.IntegerField(default=120)),
                ('cooldown_ends_at', models.DateTimeField(blank=True, null=True)),
                ('daily_reset_at', models.DateTimeField()),
                ('last_turn_taken_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kingdom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turn_limit', to='kingdoms.kingdom')),
            ],
        ),
    ]
