# Generated by Django 6.0.6 on 2026-07-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdoms', '0003_kingdom_battle_momentum_kingdom_is_at_war_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingdom',
            name='last_attacked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
