# Generated by Django 6.0.6 on 2026-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdoms', '0004_kingdom_last_attacked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingdom',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='subscription_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
