# Generated by Django 6.0.6 on 2026-07-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdoms', '0005_kingdom_is_premium_kingdom_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kingdom',
            name='food_production_modifier',
        ),
        migrations.AddField(
            model_name='kingdom',
            name='banner_colour',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='famine_production_modifier',
            field=models.FloatField(default=1.0),
        ),
    ]
