# Generated by Django 6.0.6 on 2026-07-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdoms', '0006_remove_kingdom_food_production_modifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnhistory',
            name='agriculture_investment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnhistory',
            name='infrastructure_investment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnhistory',
            name='military_investment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnhistory',
            name='welfare_investment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
