# Generated by Django 6.0.6 on 2026-07-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdoms', '0008_kingdom_crest_alter_banner_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingdom',
            name='policy_advice_exists',
            field=models.BooleanField(default=False),
        ),
    ]
