# Generated by Django 6.0.6 on 2026-07-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdoms', '0009_kingdom_policy_advice_exists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kingdom',
            name='policy_advice_exists',
        ),
        migrations.AddField(
            model_name='kingdom',
            name='policy_advice',
            field=models.TextField(blank=True),
        ),
    ]
