# Generated by Django 6.0.6 on 2026-07-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingdoms', '0011_alter_kingdom_policy_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnhistory',
            name='a_eff',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='agriculture_investment',
            field=models.FloatField(default=25),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='army_quality',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='army_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='food',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='happiness',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='infra',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='infrastructure_investment',
            field=models.FloatField(default=25),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='military_investment',
            field=models.FloatField(default=25),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='population',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='stability',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='tax_rate',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='treasury',
            field=models.FloatField(default=500),
        ),
        migrations.AlterField(
            model_name='turnhistory',
            name='welfare_investment',
            field=models.FloatField(default=25),
        ),
    ]
